config/routes.rb
Blog::Application.routes.draw do
  resources :albums

  root :to => "albums#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.haml
= form_for @album do |f|
  -if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :artist
    = f.text_field :artist
  .field
    = f.label :lead_guitarist
    = f.text_field :lead_guitarist
  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :comments
    = f.text_area :comments
  .actions
    = f.submit 'Save'

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

= link_to 'Show', @album
\|
= link_to 'Back', albums_path

app/views/albums/index.html.haml
%h1 Listing albums

%table
  %tr
    %th Title
    %th Artist
    %th Lead Guitarist
    %th Year
    %th Comments
    %th
    %th
    %th

  - @albums.each do |album|
    %tr
      %td= album.title
      %td= album.artist
      %td= album.lead_guitarist
      %td= album.year
      %td= album.comments
      %td= link_to 'Show', album
      %td= link_to 'Edit', edit_album_path(album)
      %td= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Album', new_album_path

app/views/albums/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @album.title
%p
  %b Artist:
  = @album.artist
%p
  %b Lead Guitarist:
  = @album.lead_guitarist
%p
  %b Year:
  = @album.year
%p
  %b Comments:
  = @album.comments

= link_to 'Edit', edit_album_path(@album)
\|
= link_to 'Back', albums_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    = yield